/**
 * Admin Setup Script — Global Chanakya
 * Creates the ONE permanent admin account directly in MongoDB.
 * Run with: node setup_admin.mjs
 */
import { MongoClient, ObjectId } from "mongodb";
import { createHash } from "crypto";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Parse .env manually
const envContent = fs.readFileSync(path.resolve(__dirname, ".env"), "utf-8");
let MONGODB_URI = "";
envContent.split("\n").forEach(line => {
  if (line.startsWith("MONGODB_URI=")) {
    MONGODB_URI = line.substring(line.indexOf("=") + 1).trim().replace(/^"|"$/g, "").replace(/\r/, "");
  }
});

if (!MONGODB_URI) {
  console.error("❌ MONGODB_URI not found in .env");
  process.exit(1);
}

// === Admin credentials — CHANGE THESE ===
const ADMIN_NAME = "Mukund Jha";
const ADMIN_EMAIL = "mukund@globalchanakya.com";  // your email
const ADMIN_PASSWORD = "Chanakya@Admin2024!";      // strong password
// ==========================================

// Simple password hash using SHA-256 + salt (no argon2 needed for script)
// We'll store a flag so the app uses argon2 on next login
function simpleHash(password) {
  const salt = "gc-salt-2024";
  return createHash("sha256").update(salt + password).digest("hex");
}

async function run() {
  console.log("🔗 Connecting to MongoDB Atlas...");
  const client = new MongoClient(MONGODB_URI);
  
  try {
    await client.connect();
    const db = client.db();
    const users = db.collection("users");
    
    // Check if admin already exists
    const existingAdmin = await users.findOne({ role: "admin" });
    if (existingAdmin) {
      console.log(`\n⚠️  Admin already exists: ${existingAdmin.email}`);
      console.log("   Only ONE admin is allowed. Aborting.");
      return;
    }
    
    // Check if email already registered
    const existingUser = await users.findOne({ email: ADMIN_EMAIL });
    if (existingUser) {
      // Just upgrade existing user to admin
      await users.updateOne(
        { email: ADMIN_EMAIL },
        { $set: { role: "admin", name: ADMIN_NAME, updatedAt: new Date() } }
      );
      console.log(`\n✅ Upgraded existing user to admin: ${ADMIN_EMAIL}`);
    } else {
      // Create fresh admin user
      const now = new Date();
      await users.insertOne({
        _id: new ObjectId(),
        name: ADMIN_NAME,
        email: ADMIN_EMAIL,
        // passwordHash will be regenerated by argon2 on first credentials login
        // For now store a placeholder — use Google OAuth to login instead
        passwordHash: null,
        role: "admin",
        isActive: true,
        isVerified: true,
        emailVerified: now,
        createdAt: now,
        updatedAt: now,
      });
      console.log(`\n✅ Admin account created successfully!`);
    }
    
    console.log("\n╔══════════════════════════════════════════╗");
    console.log("║        ADMIN ACCOUNT DETAILS             ║");
    console.log("╠══════════════════════════════════════════╣");
    console.log(`║  Name  : ${ADMIN_NAME.padEnd(32)}║`);
    console.log(`║  Email : ${ADMIN_EMAIL.padEnd(32)}║`);
    console.log(`║  Role  : admin                           ║`);
    console.log("╠══════════════════════════════════════════╣");
    console.log("║  LOGIN: Use Google OAuth with this email ║");
    console.log("║  (Make sure Google OAuth is configured)  ║");
    console.log("╠══════════════════════════════════════════╣");
    console.log("║  SECRET ADMIN URL:                       ║");
    console.log("║  http://localhost:3000/gc-control-9x7k   ║");
    console.log("╚══════════════════════════════════════════╝\n");
    
  } catch (err) {
    console.error("❌ Error:", err.message);
  } finally {
    await client.close();
    console.log("🔌 Connection closed.");
  }
}

run();
