const mongoose = require("mongoose");
const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env.local") });

// FORCED MODE - Check command line args
const isDryRun = process.argv.includes("--dry-run");

const MONGODB_URI = process.env.MONGODB_URI;

// Load mappings generated by expand_dictionary.js
// We must re-extract the mappings from that file or regenerate them.
// Since expand_dictionary.js wrote it into migrate_taxonomy.ts, I will just extract it from validation_data.json like expand_dictionary.js did to ensure complete consistency, or just run a combined script.

// Here is the complete combined classification logic to ensure 100% consistency with Phase 2B mapping rules without hardcoding huge JSONs:
const fs = require('fs');
const data = JSON.parse(fs.readFileSync('c:/Users/mukun/Downloads/global-chanakya-1/apps/web/validation_data.json', 'utf8'));

const COUNTRIES = new Set(["india", "china", "russia", "iran", "israel", "japan", "pakistan", "ukraine", "united states", "usa", "taiwan", "bangladesh", "maldives", "sri lanka", "myanmar", "thailand", "cambodia", "south korea", "north korea", "philippines", "indonesia", "malaysia", "singapore", "australia", "uk", "france", "germany", "italy", "spain", "poland", "romania", "nigeria", "somalia", "djibouti", "yemen", "saudi arabia", "uae", "oman", "qatar", "syria", "iraq", "egypt", "colombia", "venezuela", "cuba", "canada", "mexico", "brazil", "argentina", "turkey", "azerbaijan", "armenia", "lebanon"]);
const LEADERS = new Set(["donald trump", "narendra modi", "xi jinping", "vladimir putin", "joe biden", "khamenei", "zelensky", "kim jong un", "sheikh hasina", "muhammad yunus", "tarique rahman", "ali al-zaidi", "nicolas maduro", "miguel diaz-canel", "raul castro", "danielle smith", "mark carney", "erdogan", "mbs", "shehbaz sharif", "syrskyi", "fedorov", "lindsey graham", "piyush goyal", "macron", "scholz", "sunak", "trudeau", "albanese", "hezbollah", "nasrallah", "benjamin netanyahu", "emmanuel macron", "justin trudeau", "rishi sunak", "vladimir zelensky", "bashar al-assad", "ismail haniyeh", "yahya sinwar"]);
const REGIONS = new Set(["indo-pacific", "south asia", "middle east", "europe", "arctic", "indian ocean", "caspian sea", "black sea", "red sea", "mediterranean", "caribbean", "persian gulf", "central asia", "west africa", "north america", "global south", "latin america", "sub-saharan africa", "strait of hormuz", "south china sea (region)", "asia-pacific", "eurasia"]);
const ORGANIZATIONS = new Set(["nato", "brics", "eu", "sco", "asean", "quad", "aukus", "g20", "g7", "united nations", "imf", "world bank", "iswap", "boko haram", "jamaat-e-islami", "who", "un", "unsc", "opec", "opec+", "world health organization"]);
const CONFLICTS = new Set(["russia-ukraine war", "israel-palestine conflict", "india-pakistan conflict", "ukraine war", "gaza", "israel-hamas", "myanmar crisis", "south china sea", "yemen civil war", "sudan conflict"]);
const TOPICS = new Set(["nuclear deterrence", "dollar hegemony", "strategic autonomy", "multipolarity", "economic security", "cyber warfare", "diplomacy", "digital currency race", "drone warfare", "supply chain security", "nuclear energy", "gray-zone warfare", "disinformation", "ai deepfakes", "cyber espionage", "sovereign debt", "climate risk", "critical minerals", "de-dollarization", "trade war", "sanctions", "energy security", "artificial intelligence", "semiconductors", "rare earths", "military modernization", "terrorism"]);

const UTILITY_KEYWORDS = ["intelligence", "brief", "analysis", "insight", "weekly", "daily", "monthly", "report", "update"];

const slugify = (str) => str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, "");
const normalizeName = (str) => {
  if (str.toLowerCase() === "usa") return "United States";
  if (str.toLowerCase() === "eu") return "European Union";
  return str.split(" ").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
};

let categoryMap = new Map();
let tagMap = new Map();

for (const blog of data.blogs) {
  if (blog.category) {
    if (!categoryMap.has(blog.category)) categoryMap.set(blog.category, { count: 0, val: blog.category });
    categoryMap.get(blog.category).count++;
  }
  if (Array.isArray(blog.tags)) {
    for (const tag of blog.tags) {
      if (!tagMap.has(tag)) tagMap.set(tag, { count: 0, val: tag });
      tagMap.get(tag).count++;
    }
  }
}

const sortedCategories = Array.from(categoryMap.values()).sort((a, b) => b.count - a.count);
const sortedTags = Array.from(tagMap.values()).sort((a, b) => b.count - a.count);

const FINAL_CATEGORY_MAP = {};
const FINAL_TAG_MAP = {};

sortedCategories.forEach(({val}) => {
  let mappedType = "Category";
  let norm = normalizeName(val);
  if (val.toLowerCase() === "middle east" || val.toLowerCase() === "indo-pacific" || val.toLowerCase() === "south asia" || val.toLowerCase() === "europe") {
    mappedType = "Region";
  } else if (val.toLowerCase() === "china" || val.toLowerCase() === "russia" || val.toLowerCase() === "usa") {
    mappedType = "Country";
  } else if (val.toLowerCase() === "economy") {
    norm = "Economy & Trade";
  }
  FINAL_CATEGORY_MAP[val] = { type: mappedType, normalized: norm, slug: slugify(norm) };
});

sortedTags.forEach(({val, count}) => {
  let lower = val.toLowerCase().trim();
  let mappedType = null;
  if (UTILITY_KEYWORDS.some(kw => lower.includes(kw))) { mappedType = "IGNORE"; }
  else if (COUNTRIES.has(lower)) { mappedType = "Country"; }
  else if (LEADERS.has(lower)) { mappedType = "Leader"; }
  else if (REGIONS.has(lower)) { mappedType = "Region"; }
  else if (ORGANIZATIONS.has(lower)) { mappedType = "Organization"; }
  else if (CONFLICTS.has(lower)) { mappedType = "Conflict"; }
  else if (TOPICS.has(lower)) { mappedType = "Topic"; }
  
  if (mappedType && mappedType !== "IGNORE") {
    let norm = normalizeName(val);
    if (lower === "usa") norm = "United States";
    if (lower === "south china sea") mappedType = "Conflict";
    FINAL_TAG_MAP[val] = { type: mappedType, normalized: norm, slug: slugify(norm) };
  }
});


async function runMigration() {
  if (!MONGODB_URI) throw new Error("Missing MONGODB_URI");

  const url = new URL(MONGODB_URI);
  console.log(`Starting Taxonomy Migration in ${isDryRun ? "DRY-RUN" : "PRODUCTION EXECUTION"} mode...\n`);
  console.log(`Database Name: ${url.pathname.slice(1)}`);
  console.log(`Host: ${url.hostname}`);

  await mongoose.connect(MONGODB_URI);

  const blogSchema = new mongoose.Schema({}, { strict: false });
  const Blog = mongoose.models.Blog || mongoose.model('Blog', blogSchema, 'blogs');
  
  // Generic entity schema for upserts
  const entitySchema = new mongoose.Schema({ name: String, slug: String }, { strict: false });
  
  const entities = {
    Category: mongoose.models.Category || mongoose.model('Category', entitySchema, 'categories'),
    Region: mongoose.models.Region || mongoose.model('Region', entitySchema, 'regions'),
    Country: mongoose.models.Country || mongoose.model('Country', entitySchema, 'countries'),
    Topic: mongoose.models.Topic || mongoose.model('Topic', entitySchema, 'topics'),
    Leader: mongoose.models.Leader || mongoose.model('Leader', entitySchema, 'leaders'),
    Conflict: mongoose.models.Conflict || mongoose.model('Conflict', entitySchema, 'conflicts'),
    Organization: mongoose.models.Organization || mongoose.model('Organization', entitySchema, 'organizations'),
  };

  const blogs = await Blog.find({}).lean();
  console.log(`Total blogs scanned: ${blogs.length}`);

  let stats = {
    expectedDatabaseWrites: 0,
    expectedBlogUpdates: 0,
    proposedEntities: {
      Category: new Map(),
      Region: new Map(),
      Country: new Map(),
      Topic: new Map(),
      Leader: new Map(),
      Conflict: new Map(),
      Organization: new Map(),
    }
  };

  // Determine what entities we need
  for (const blog of blogs) {
    if (blog.category) {
      const mapped = FINAL_CATEGORY_MAP[blog.category];
      if (mapped) {
        stats.proposedEntities[mapped.type].set(mapped.slug, mapped.normalized);
      }
    }
    if (Array.isArray(blog.tags)) {
      for (const tag of blog.tags) {
        const mapped = FINAL_TAG_MAP[tag];
        if (mapped && mapped.type !== "IGNORE") {
          stats.proposedEntities[mapped.type].set(mapped.slug, mapped.normalized);
        }
      }
    }
  }

  // Calculate stats
  for (const type in stats.proposedEntities) {
    stats.expectedDatabaseWrites += stats.proposedEntities[type].size;
  }

  // Find blogs that actually require updates
  let updateOperations = [];
  
  for (const blog of blogs) {
    let relationships = {
      Category: new Set(), Region: new Set(), Country: new Set(),
      Topic: new Set(), Leader: new Set(), Conflict: new Set(), Organization: new Set()
    };
    
    let hasUpdates = false;

    if (blog.category && FINAL_CATEGORY_MAP[blog.category]) {
      const mapped = FINAL_CATEGORY_MAP[blog.category];
      relationships[mapped.type].add(mapped.slug);
      hasUpdates = true;
    }
    if (Array.isArray(blog.tags)) {
      for (const tag of blog.tags) {
        if (FINAL_TAG_MAP[tag]) {
          const mapped = FINAL_TAG_MAP[tag];
          relationships[mapped.type].add(mapped.slug);
          hasUpdates = true;
        }
      }
    }

    if (hasUpdates) {
      updateOperations.push({ blogId: blog._id, relationships });
    }
  }

  stats.expectedBlogUpdates = updateOperations.length;
  stats.expectedDatabaseWrites += updateOperations.length;

  console.log("\\n=== DRY-RUN REPORT ===");
  console.log("Blogs Scanned: " + blogs.length);
  console.log("\\nProposed Entities By Type:");
  console.log("- Categories: " + stats.proposedEntities.Category.size);
  console.log("- Topics: " + stats.proposedEntities.Topic.size);
  console.log("- Countries: " + stats.proposedEntities.Country.size);
  console.log("- Regions: " + stats.proposedEntities.Region.size);
  console.log("- Conflicts: " + stats.proposedEntities.Conflict.size);
  console.log("- Leaders: " + stats.proposedEntities.Leader.size);
  console.log("- Organizations: " + stats.proposedEntities.Organization.size);

  if (isDryRun) {
    console.log("\\n[DRY RUN CONFIRMATION]: ZERO database writes performed.");
    await mongoose.disconnect();
    return;
  }

  // EXECUTION MODE
  console.log("\\n[EXECUTION]: Starting write operations...");
  const slugToIdMap = {
    Category: new Map(), Region: new Map(), Country: new Map(),
    Topic: new Map(), Leader: new Map(), Conflict: new Map(), Organization: new Map()
  };

  // 1. Entity Upserts (Order: Category, Region, Country, Topic, Leader, Conflict, Organization)
  const order = ['Category', 'Region', 'Country', 'Topic', 'Leader', 'Conflict', 'Organization'];
  for (const type of order) {
    const entityMap = stats.proposedEntities[type];
    if (entityMap.size === 0) continue;
    
    console.log(`Upserting ${type}s (${entityMap.size})...`);
    
    const bulkOps = Array.from(entityMap.entries()).map(([slug, name]) => ({
      updateOne: {
        filter: { slug },
        update: { $set: { name, slug } },
        upsert: true
      }
    }));

    await entities[type].bulkWrite(bulkOps);

    // Fetch back the ObjectIds for relationship mapping
    const docs = await entities[type].find({ slug: { $in: Array.from(entityMap.keys()) } }, { _id: 1, slug: 1 }).lean();
    for (const doc of docs) {
      slugToIdMap[type].set(doc.slug, doc._id);
    }
  }

  // 2. Blog Updates
  console.log(`\nUpdating Blogs (${updateOperations.length})...`);
  const blogBulkOps = [];
  
  for (const op of updateOperations) {
    const updateSet = {};
    const addToSet = {};
    
    if (op.relationships.Category.size > 0) {
      const slug = Array.from(op.relationships.Category)[0]; // Only 1 category allowed usually, we take the first mapped
      updateSet.categoryId = slugToIdMap.Category.get(slug);
    }
    
    const arrayFields = [
      { key: 'topics', type: 'Topic' },
      { key: 'countries', type: 'Country' },
      { key: 'regions', type: 'Region' },
      { key: 'leaders', type: 'Leader' },
      { key: 'conflicts', type: 'Conflict' },
      { key: 'organizations', type: 'Organization' }
    ];

    for (const field of arrayFields) {
      const slugs = Array.from(op.relationships[field.type]);
      if (slugs.length > 0) {
        addToSet[field.key] = { $each: slugs.map(slug => slugToIdMap[field.type].get(slug)) };
      }
    }

    const updateQuery = {};
    if (Object.keys(updateSet).length > 0) updateQuery.$set = updateSet;
    if (Object.keys(addToSet).length > 0) updateQuery.$addToSet = addToSet;

    if (Object.keys(updateQuery).length > 0) {
      blogBulkOps.push({
        updateOne: {
          filter: { _id: op.blogId },
          update: updateQuery
        }
      });
    }
  }

  if (blogBulkOps.length > 0) {
    const batchSize = 50;
    for (let i = 0; i < blogBulkOps.length; i += batchSize) {
      const batch = blogBulkOps.slice(i, i + batchSize);
      await Blog.bulkWrite(batch);
      console.log(`Processed blog batch ${i/batchSize + 1}`);
    }
  }

  console.log("\n[EXECUTION CONFIRMATION]: Migration completed.");
  await mongoose.disconnect();
}

runMigration().catch(console.error);
