/**
 * contentTemplates.ts
 * Stores programmatic templates for rapidly scaling 1000+ SEO pages.
 */

export const SEO_TEMPLATES = {
  COUNTRY_BRIEF: `
# 🌍 Strategic Brief: {{countryName}}

## 1. Geopolitical Positioning
{{countryName}} currently maintains a {{politicalStance}} stance in the {{region}} region. Its strategic importance is primarily driven by {{coreDriver}}.

## 2. Active Conflicts & Escalations
{{activeConflictsList}}

## 3. Major Alliances
{{countryName}} is a pivotal member of {{alliancesList}}, anchoring its defense and economic policies against regional competitors.

## 4. Economic & Defense Indicators
- **GDP:** {{gdp}}
- **Intelligence Score:** {{intelScore}}/100
- **Defense Posture:** {{defensePosture}}

*Generated by Global Chanakya Intelligence Engine on {{date}}*
  `.trim(),

  LEADER_PROFILE: `
# 👤 Leader Profile: {{leaderName}}

## Background & Rise to Power
{{leaderName}}, currently acting as {{role}} of {{countryName}}, assumed office in {{year}}. 

## Core Policy Focus
{{policyFocusList}}

## Strategic Influence
Through alliances with {{associatedAlliances}}, {{leaderName}} exerts significant influence over the {{region}} balance of power.
  `.trim(),
};
